### PR TITLE
fixes for omnetpp5.4.1 inet3.6.5

### PR DESCRIPTION
**Pull request by ZoltanBojthe**
fixes for omnetpp5.4.1 and inet3.6.5

### CODE REVIEW

**Comment by Musteblume** [comment]
Hi,
thank you for the pull request. Sadly CoRE4INET is not linking against INET  3.6.5 in OMNeT++ 5.4.1 and Windows. I think this is related with this INET issue: https://github.com/inet-framework/inet/issues/379. I tried different workarounds discussed in this and related issues. Did you tried it on Windows or have any hints?

**Comment by rhornig** [comment]
I will take a look. I can conform the with clang, you cannot link to INET from a dependent project. This is of course not related to this PR, bit generally an issue with INET/OMNET/WINDOWS/CLANG. Classes that define only pure virtual functions and a virtual inline destructor do not generate properly exported type info. I'm looking into how to force this apart from the trivial (and painful) workaround of adding the empty destructors for all interface calsses to a separate compilation unit. I would like to avoid this if possible...

**Comment by rhornig** [comment]
It seems that with some magic it is possible to force clang to add ne missing exports (by specifying them in a .DEF file for the linker.) I will create a patched version of INET 3.6.x that would create proper .DLL files also with clang. Stay tuned.

**Comment by rhornig** [comment]
@Musteblume I have created a patch that would workaround the linking issue on clang/windows. Would you mind to test it? I was able to successfully build/link Core4INET, but would love to see if it works for you too:

https://github.com/inet-framework/inet/commit/6937f43e5f94216d022fdf7556cbd4c29e256ffd

**Comment by Musteblume** [comment]
@rhornig thats promising. I will test it when i am back to office on tuesday. I will report my results. Thank you for your valuable work.

**Comment by Musteblume** [comment]
@rhornig i checked with the  origin/v3.x branch and it is building, linking and our tests are successful on my Windows 10 machine. I will try to merge this pull request in the next days/weeks.

**Comment by rhornig** [comment]
Great. Then I will release INET 3.6.6 so you can specify that as a dependency.

**Comment by ZoltanBojthe** [comment]
Now rebased and updated for current master

**Pull request merged**
